theme: jekyll-theme-minimal

title: "Piano Transcription"
description: "This app transcribes audio/video to MIDI and then 3D-piano plays it, and can optionally advise finger numbers"
logo: https://raw.GitHubUserContent.com/BShakhovsky/PianoTranscription_Android/master/app/src/main/res/drawable-nodpi/google_play_icon.webp
google_analytics: UA-154921770-1

include: .well-known
